# Generated by Django 4.0.4 on 2022-06-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=120, verbose_name='Icono')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('image_movil', models.URLField(max_length=255, verbose_name='Imagen movil')),
                ('image_tablet', models.URLField(max_length=255, verbose_name='Imagen tablet')),
                ('image_desktop', models.URLField(max_length=255, verbose_name='Imagen escritorio')),
                ('github', models.URLField(max_length=255, verbose_name='Repositorio')),
                ('live', models.URLField(blank=True, max_length=255, null=True, verbose_name='Demo')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('techologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portafolio.technology', verbose_name='Tecnologias')),
            ],
        ),
    ]
