# Generated by Django 4.0.4 on 2022-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('school', models.CharField(max_length=100, verbose_name='Escuela')),
                ('year', models.CharField(max_length=10, verbose_name='Año')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formaciones',
                'db_table': 'Formaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=120, verbose_name='Icono')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'db_table': 'Tecnologias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('image', models.URLField(max_length=255, verbose_name='Imagen')),
                ('github', models.URLField(max_length=255, verbose_name='Repositorio')),
                ('live', models.URLField(blank=True, max_length=255, null=True, verbose_name='Demo')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('techologies', models.ManyToManyField(to='Portafolio.technology', verbose_name='Tecnologias')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'Proyectos',
                'ordering': ['id'],
            },
        ),
    ]
