# Generated by Django 4.0.4 on 2022-06-07 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['id'], 'verbose_name': 'Tecnologia', 'verbose_name_plural': 'Tecnologias'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='Proyectos',
        ),
        migrations.AlterModelTable(
            name='technology',
            table='Tecnologias',
        ),
    ]
