# Generated by Django 4.0.4 on 2022-06-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0002_alter_project_options_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='techologies',
        ),
        migrations.AddField(
            model_name='project',
            name='techologies',
            field=models.ManyToManyField(to='Portafolio.technology', verbose_name='Tecnologias'),
        ),
    ]
