# Generated by Django 4.0.4 on 2022-06-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0003_remove_project_techologies_project_techologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_desktop',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_movil',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_tablet',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(default=' ', max_length=255, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
