# Generated by Django 4.0.4 on 2022-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0004_remove_project_image_desktop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('school', models.CharField(max_length=100, verbose_name='Escuela')),
                ('year', models.CharField(max_length=10, verbose_name='Año')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formaciones',
                'db_table': 'Formaciones',
                'ordering': ['id'],
            },
        ),
    ]
